# Shared tmux config. Consumed by:
#   - home/common.nix    (programs.tmux.extraConfig = builtins.readFile ./tmux/tmux.conf)
#   - home/devshell.nix  (tmux -f ./tmux/tmux.conf)

set -g prefix C-a
unbind C-b
bind C-a send-prefix

setw -g mode-keys vi
set -g mouse on
set -g history-limit 9999999
set -sg escape-time 0
set -g default-terminal "tmux-256color"

bind v split-window -h
bind s split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -T copy-mode-vi V send-keys -X begin-selection
bind -T copy-mode-vi Y send-keys -X copy-pipe-and-cancel "wl-copy"

unbind-key -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi y send-keys -X copy-selection

set -g xterm-keys on
